export const FETCH_CHANNEL_REQUEST = "FETCH_CHANNEL_REQUEST";
export const FETCH_CHANNEL_SUCCESS = "FETCH_CHANNEL_SUCCESS";
export const FETCH_CHANNEL_ERROR = "FETCH_CHANNEL_ERROR";

export const ADD_NEW_CHANNEL_REQUEST = "ADD_NEW_CHANNEL_REQUEST";
export const ADD_NEW_CHANNEL_SUCCESS = "ADD_NEW_CHANNEL_SUCCESS";
export const ADD_NEW_CHANNEL_ERROR = "ADD_NEW_CHANNEL_ERROR";

export const ADD_NEW_VALUES_REQUEST = "ADD_NEW_VALUES_REQUEST";
export const ADD_NEW_VALUES_SUCCESS = "ADD_NEW_VALUES_SUCCESS";
export const ADD_NEW_VALUES_ERROR = "ADD_NEW_VALUES_ERROR";
